CREATE TABLE GROUND_TEMPERATURE (
   "ID" INTEGER not null primary key,
    "TIME" INTEGER,
    "TEMPERATURE" INTEGER
);

CREATE TABLE AIR_TEMPERATURE (
   "ID" INTEGER not null primary key,
    "TIME" INTEGER,
    "TEMPERATURE" INTEGER
);